services:
  backend:
    build: ./backend
    container_name: bitcoin-backend
    ports:
      - "8000:80" 
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - bitcoin-net

  frontend:
    build: ./frontend
    container_name: bitcoin-frontend
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - bitcoin-net

  db:
    image: postgres:16
    container_name: bitcoin-db
    restart: always
    environment:
      POSTGRES_USER: bitcoin
      POSTGRES_PASSWORD: bitcoin
      POSTGRES_DB: bitcoin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bitcoin-net

volumes:
  pgdata:
  node_modules:

networks:
  bitcoin-net:
    driver: bridge